// ! Do Not Edit This File
import { Icons } from "../icons";

export const TrashButton = ({ onClick }: { onClick: () => void }) => (
  <img
    src={Icons.Trash}
    alt=""
    className="trash-button"
    style={{
      width: 40,
      border: 0,
    }}
    onClick={() => {
      onClick();
    }}
  />
);
